### PR TITLE
fix: use upstream minio-operator

### LINKED ISSUE #20: Failed to publish the  new custom-built image for minio
There is two issues: 

- Need to “squash” the layers together, but this doesn’t work on GitHub actions since experimental docker features aren’t enabled. This is due to a “feature” where the operator downloads the executable from the largest layer in the image.
- We need a .sha256sum and .minisign (https://jedisct1.github.io/minisign/) https://github.com/minio/operator/blob/79ff2c294728030a88f29e171dcc96952cbf6bdd/pkg/controller/cluster/main-controller.go#L559. These don’t exist in a custom-built image

Kind environment was required for testing minio-operator with a minio image. Instructions for this setup have been added to the README of this repo.

### PR DESCRIPTION
**Pull request by JessicaBarh**
Resolves #20 

within a kind environment, I've tested minio using the following images:
`kubectl get deployment minio-operator -n minio-operator -o json | jq '.spec.template.spec.containers[0].image'
"minio/operator:v4.0.11"`

and 

`kubectl get tenants.minio.min.io minio-tenant-1 -n minio-tenant-1 -o json | jq '.spec.image'
"k8scc01covidacr.azurecr.io/minio/minio:45627b98"`

### CODE REVIEW

**Comment by blairdrummond** [comment]
Hey @JessicaBarh , can you tidy up the `kind` deployment into a little folder with a README? That'll give some instructions so that we can test it. Then just load that folder here as a zip

**Comment by JessicaBarh** [comment]
> Hey @JessicaBarh , can you tidy up the `kind` deployment into a little folder with a README? That'll give some instructions so that we can test it. Then just load that folder here as a zip

Yep! just pushed a new commit updating the readme of this repo to include instructions for development with the required files. my kind environment was too large to zip and upload in my commit but the instructions should pretty much replicate what I had.

**Comment by JessicaBarh** [comment]
Once https://github.com/StatCan/minio/pull/4 is merged and a new Minio image is pushed to ACR, the current minio tenant image used here can be replaced for the custom-built Minio image:
https://github.com/StatCan/minio-operator/blob/master/instances/base/tenant.yaml#L75

**Review by blairdrummond — APPROVED** [review]
Worked great! I added a patch to the `imagePullPolicy` so that I could `kind load` and then use the acr image, but aside from that worked perfectly

Screenshot from 2021-05-28 10-41-22

**Comment by blairdrummond** [comment]
@zachomedia  Her README has solid instructions for deploying, I had it up and running in 10 minutes. I used the image

```
docker pull k8scc01covidacr.azurecr.io/minio/minio:11b58498
# kind load ^
```

**Comment by JessicaBarh** [comment]
A new minio image was created yesterday that includes the rebasing onto upstream https://github.com/StatCan/minio/runs/2713780999. Should use that one instead so I'll push a new commit with that change now!

**Review by zachomedia — APPROVED** [review]

**Pull request merged**
