### PR TITLE
DRAFT: chore(standard): add 4TB to minio standard

### PR DESCRIPTION
**Pull request by blairdrummond**
@sylus  is this the correct way to increase the size of MinIO?

### CODE REVIEW

**Comment by blairdrummond** [comment]
@brendangadd can you give a :+1: ?

**Comment by brendangadd** [comment]
* @blairdrummond I'm giving :+1: for expanding our storage to meet the need.
* @blairdrummond I think we scale storage by adding instances, not adjusting PV size. I'm concerned this method would be destructive.
* @sylus Immediate DAaaS priority is enabling you to do the KF v1.2 deployment on your desired timeline. If this MinIO work, or anything, interferes with that, then feel free to push it off to next sprint – no questions asked.

/cc @zachomedia

**Comment by blairdrummond** [comment]
:pray: Thanks @brendangadd ! Happy to close this PR and open a new one, just wasn't sure how that was configured.

**Comment by blairdrummond** [comment]
*Marked as draft so that it won't accidentally cause destructive behaviour*

**Comment by sylus** [comment]
ATM there are 4 2TB disks per pod, I think we have more than enough capacity so can re-assess after security review.

**Pull request closed without merging**
